#!/bin/bash

# This script prepares the environment for the Mars Credit Miner app

echo "===== Mars Credit Miner - App Helper ====="
echo "Setting up environment for the app..."

# Set up directories
DATA_DIR="$HOME/.marscredit"
KEYSTORE_DIR="$DATA_DIR/keystore"
LOG_DIR="$DATA_DIR/logs"
ETHASH_DIR="$DATA_DIR/.ethash"
GETH_DIR="$DATA_DIR/geth"
CHAINDATA_DIR="$GETH_DIR/chaindata"

mkdir -p "$DATA_DIR" "$KEYSTORE_DIR" "$LOG_DIR" "$ETHASH_DIR" "$GETH_DIR" "$CHAINDATA_DIR"

# Kill any existing geth processes
echo "Terminating any existing geth processes..."
pkill -f geth || true
sleep 3

# Check if port 8546 is already in use
PORT_CHECK=$(lsof -i:8546 | grep LISTEN)
if [ ! -z "$PORT_CHECK" ]; then
    echo "WARNING: Port 8546 is already in use. Attempting to free it..."
    sudo lsof -i:8546 -sTCP:LISTEN | awk 'NR>1 {print $2}' | xargs sudo kill -9 || true
    sleep 2
fi

# Copy our geth binary to the expected locations
if [ -f "Resources/geth/geth" ]; then
    echo "Copying geth binary to ~/.marscredit/geth-binary"
    cp Resources/geth/geth "$DATA_DIR/geth-binary"
    chmod +x "$DATA_DIR/geth-binary"
else
    echo "Error: geth binary not found in Resources/geth/"
    if [ -f "$DATA_DIR/geth-binary" ]; then
        echo "Using existing geth binary from $DATA_DIR/geth-binary"
    else
        echo "No geth binary found. Cannot proceed."
        exit 1
    fi
fi

# Create a proper genesis file if it doesn't exist
GENESIS_FILE="$DATA_DIR/genesis.json"

if [ ! -f "$GENESIS_FILE" ]; then
    echo "Creating genesis file..."
    cat > "$GENESIS_FILE" << EOF
{
  "config": {
    "chainId": 110110,
    "homesteadBlock": 0,
    "eip150Block": 0,
    "eip155Block": 0,
    "eip158Block": 0,
    "byzantiumBlock": 0,
    "constantinopleBlock": 0,
    "petersburgBlock": 0,
    "istanbulBlock": 0,
    "berlinBlock": 0,
    "ethash": {}
  },
  "nonce": "0x0000000000000042",
  "timestamp": "0x0",
  "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "extraData": "0x",
  "gasLimit": "0x1c9c380",
  "difficulty": "0x400",
  "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "coinbase": "0x0000000000000000000000000000000000000000",
  "alloc": {}
}
EOF
fi

# Initialize the blockchain if needed
if [ ! -d "$CHAINDATA_DIR" ] || [ -z "$(ls -A "$CHAINDATA_DIR")" ]; then
    echo "Initializing blockchain with genesis block..."
    "$DATA_DIR/geth-binary" --datadir "$DATA_DIR" init "$GENESIS_FILE"
fi

# Set up a wrapper script for the app to use
WRAPPER_SCRIPT="$DATA_DIR/run_geth_wrapper.sh"
cat > "$WRAPPER_SCRIPT" << EOF
#!/bin/bash

# Wrapper script for Mars Credit Miner app
# Do not modify - this file is generated by app_helper.sh

# Kill any existing geth processes
pkill -f geth || true
sleep 2

# Check if port 8546 is already in use
PORT_CHECK=\$(lsof -i:8546 | grep LISTEN)
if [ ! -z "\$PORT_CHECK" ]; then
    echo "WARNING: Port 8546 is already in use. Attempting to free it..."
    lsof -i:8546 -sTCP:LISTEN | awk 'NR>1 {print \$2}' | xargs kill -9 || true
    sleep 2
fi

# Start geth with optimized settings for Apple Silicon
\$HOME/.marscredit/geth-binary \\
    --datadir "\$HOME/.marscredit" \\
    --keystore "\$HOME/.marscredit/keystore" \\
    --syncmode "full" \\
    --http \\
    --http.addr "localhost" \\
    --http.port "8546" \\
    --http.api "personal,eth,net,web3,miner,admin" \\
    --http.vhosts "*" \\
    --http.corsdomain "*" \\
    --networkid "110110" \\
    --nat "any" \\
    --maxpeers "25" \\
    --cache "512" \\
    --bootnodes "enode://ca3639067a580a0f1db7412aeeef6d5d5e93606ed7f236a5343fe0d1115fb8c2bea2a22fa86e9794b544f886a4cb0de1afcbccf60960802bf00d81dab9553ec9@monorail.proxy.rlwy.net:26254,enode://7f2ee75a1c112735aaa43de1e5a6c4d7e07d03a5352b5782ed8e0c7cc046a8c8839ad093b09649e0b4a6ed8900211fb4438765c99d07bb00006ef080a1aa9ab6@viaduct.proxy.rlwy.net:30270,enode://98710174f4798dae1931e417944ac7a7fb3268d38ef8d3941c8fcc44fe178b118003d8b3d61d85af39c561235a1708f8dd61f8ba47df4c4a6b9156e272af2cfc@monorail.proxy.rlwy.net:29138" \\
    --nousb \\
    > "\$HOME/.marscredit/logs/geth.log" 2>&1 &

# Store the PID
echo \$! > "\$HOME/.marscredit/geth.pid"

echo "Geth node started on port 8546 (PID: \$(cat \$HOME/.marscredit/geth.pid))"
echo "Waiting for RPC connection to become available..."

# Wait for the RPC endpoint to become available
MAX_ATTEMPTS=30
for ((i=1; i<=MAX_ATTEMPTS; i++)); do
    if curl -s -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"net_version","params":[],"id":1}' http://localhost:8546 > /dev/null 2>&1; then
        echo "RPC endpoint is available!"
        exit 0
    fi
    
    echo "Waiting for RPC connection (attempt \$i/\$MAX_ATTEMPTS)..."
    sleep 2
done

echo "WARNING: RPC endpoint did not become available within the timeout period"
echo "Check geth.log for errors"
cat "\$HOME/.marscredit/logs/geth.log" | tail -20
exit 1
EOF

chmod +x "$WRAPPER_SCRIPT"

# Run the wrapper script to start geth
echo "Starting geth node..."
"$WRAPPER_SCRIPT"

echo "===== Setup Complete ====="
echo "To use the app:"
echo "1. The geth binary is now properly installed in the Resources/geth directory"
echo "2. A wrapper script has been created at $WRAPPER_SCRIPT"
echo "3. When you click 'Start Mining', you should see the Mars planet with spinning moon"
echo ""
echo "If you still encounter issues, check the logs at $LOG_DIR/geth.log" 